name: Docker Publish SafeGuard

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docker-build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Show workspace
        shell: powershell
        run: |
          Write-Host "GITHUB_WORKSPACE = $env:GITHUB_WORKSPACE"
          Get-Location
          Get-ChildItem $env:GITHUB_WORKSPACE
          Get-ChildItem "$env:GITHUB_WORKSPACE\SafeGuard"

      - name: Show Docker version
        shell: powershell
        run: docker version

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        shell: powershell
        run: nuget restore "$env:GITHUB_WORKSPACE\SafeGuard\SafeGuard.sln"

      - name: Build ASP.NET web project
        shell: powershell
        run: msbuild "$env:GITHUB_WORKSPACE\SafeGuard\SafeGuard.csproj" /p:Configuration=Release

      - name: Create Publish folder manually
        shell: powershell
        run: |
          $projectPath = "$env:GITHUB_WORKSPACE\SafeGuard"
          $publishPath = "$env:GITHUB_WORKSPACE\Publish"

          if (Test-Path $publishPath) {
            Remove-Item -Recurse -Force $publishPath
          }

          New-Item -ItemType Directory -Force -Path $publishPath | Out-Null

          Copy-Item "$projectPath\bin" -Destination "$publishPath\bin" -Recurse -Force
          Copy-Item "$projectPath\Content" -Destination "$publishPath\Content" -Recurse -Force
          Copy-Item "$projectPath\Views" -Destination "$publishPath\Views" -Recurse -Force
          Copy-Item "$projectPath\Global.asax" -Destination "$publishPath\Global.asax" -Force
          Copy-Item "$projectPath\Web.config" -Destination "$publishPath\Web.config" -Force

      - name: Show published files
        shell: powershell
        run: |
          $publishPath = "$env:GITHUB_WORKSPACE\Publish"
          Write-Host "Checking publish path: $publishPath"
          Get-ChildItem $publishPath
          Get-ChildItem "$publishPath\bin" | Select-Object -First 5

      - name: Docker login
        shell: powershell
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build Docker image
        shell: powershell
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/safeguard-web:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/safeguard-web:${{ github.run_number }} .

      - name: Push latest tag
        shell: powershell
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/safeguard-web:latest

      - name: Push numbered tag
        shell: powershell
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/safeguard-web:${{ github.run_number }}
